### ISSUE TITLE
NPE with Dynamic Trees

### ISSUE THREAD

**Issue by Adaptivity** [Insane-96/IguanaTweaksReborn#14]
[This](https://pastebin.com/zUC2fXqQ) appears in logs a lot of times. Not sure which mod fault is it but dynamic trees open source so you can take a look what's wrong (https://github.com/ferreusveritas/DynamicTrees)

**Comment by Insane-96** [comment]
I'll look into it. Thanks

**Comment by Insane-96** [comment]
Summoning @ferreusveritas

**Comment by ferreusveritas** [comment]
net.insane96mcp.iguanatweaks.modules.ModuleGeneral.java:61
`hardness = block.getBlockHardness(null, null, null);`  <- Blockstate is passed as a null

com.ferreusveritas.dynamictrees.blocks.BlockBranch.java:211
`int radius = getRadius(world, pos);` <- world is now null

com.ferreusveritas.dynamictrees.blocks.BlockBranch.java:269
`return getRadius(blockAccess.getBlockState(pos));`  <- blockAccess is null.  Boom.. NPE

So is it acceptable to use null for all the parameters in getBlockHardness?

**Comment by Insane-96** [comment]
I didn't put a world because vanilla method returns blockHardness without need of any of those parameters

**Comment by ferreusveritas** [comment]
The parameters are there for a reason.  The default implementation may not require it because hardness is constant for simple blocks.  If it was a rule that hardness was always constant for a given block type then the blockHardness member function would have no parameters at all.  If you don't provide these then you're going to  run into crashes with other mods in the future that don't have constant hardness for it's block.  Why not set them now and live happily ever after?

**Comment by Insane-96** [comment]
I'll fix it. I need to loop through all block states so it will no longer be a problem
