### ISSUE TITLE
Crash with Crossroads

### ISSUE THREAD

**Issue by CraftyZombie** [Insane-96/IguanaTweaksReborn#271]
Not following this guidline will result in ignored and closed issue.  
Please make sure you're using the latest versions before sending a report.

**Versions**:
* Minecraft:  1.20.1
* Forge: 47.2.20
* IguanaTweaks Reborn: 3.2.1
* InsaneLib: 1.12.1

**What Happens**:  
When Crossroads (https://github.com/Crossroads-Development/Crossroads) is installed, the game crashes upon attempted world creation.

//Please send logs even if you don't have any crash  
//**Use Gist or Pastebin**  
**Logs / Crash reports**:  
https://gist.github.com/CraftyZombie/850b5a2a0156302a046babadf7078d31

//If different from default
**Config**:  
N/A

**Can be reproduced with a minimal set of mods? (IguanaTweaks Reborn + InsaneLib + e.g. Quark)?**:  
Yes:

- crossroads-1.20.1-2.10.1
- essentials-1.20.1-2.16.0
- IguanaTweaksReborn-3.2.1-mc1.20.1
- InsaneLib-1.12.1-mc1.20.1
- MaxHealthFix-Forge-1.20.1-12.0.2

**Comment by CraftyZombie** [comment]
https://github.com/Crossroads-Development/Crossroads/issues/278

**Comment by Da-Technomancer** [comment]
Pretty sure the cause is that the 'edible blob' from Crossroads, which is edible, but doesn't use food properties because the hunger restored is dynamic. 

Relevant Crossroads item: https://github.com/Crossroads-Development/Crossroads/blob/1.20.1/src/main/java/com/Da_Technomancer/crossroads/items/EdibleBlob.java
Relevant Iguana Tweaks code that doesn't like edible items not using food properties: https://github.com/Insane96/IguanaTweaksReborn/blob/1.20.1/src/main/java/insane96mcp/iguanatweaksreborn/module/hungerhealth/fooddrinks/FoodDrinks.java#L183-L197

Is the better fix here for Crossroads to add the edible blob to the hunger tweaks blacklist tag, or something else?

**Comment by Insane96** [comment]
Uhm, ok it does return true even without food properties. Well I guess I can't expect `isEdible` to be always true if `foodProperties != null`. I will add a null check to it.

**Comment by Insane96** [comment]
Fixed for next ITR Release
